<a href="https://colab.research.google.com/github/GaurangRawat/Machine-Learning-Projects/blob/main/ML%20Algorithms/Ridge_Regression_and_Elastic_Net_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LinearRegression, Lasso, Ridge , ElasticNet
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
california = fetch_california_housing()
data = pd.DataFrame(california.data, columns=california.feature_names)
data['MedHouseVal'] = california.target

In [3]:
data.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  MedHouseVal  
0    -122.23        4.526  
1    -122.22        3.585  
2    -122.24        3.521  
3    -122.25        3.413  
4    -122.25        3.422

In [4]:
X = data.drop('MedHouseVal', axis=1)
y = data['MedHouseVal']

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [6]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

##**Apply Linear Regression**

---



In [7]:
linear_reg = LinearRegression()
linear_reg.fit(X_train, y_train)
y_pred_linear = linear_reg.predict(X_test)

mse_linear = mean_squared_error(y_test, y_pred_linear)
r2_linear = r2_score(y_test, y_pred_linear)

In [8]:
print(f"MSE Linear Reg : {mse_linear}")

MSE Linear Reg : 0.5558915986952442


In [9]:
print(f"R2 Linear Reg : {r2_linear}")

R2 Linear Reg : 0.575787706032451


##**Apply Lasso Regression**

---

In [10]:
lasso_reg = Lasso(alpha=0.1)
lasso_reg.fit(X_train, y_train)
y_pred_lasso = lasso_reg.predict(X_test)
mse_lasso = mean_squared_error(y_test, y_pred_lasso)
r2_lasso = r2_score(y_test, y_pred_lasso)

In [11]:
print(f"MSE Lasso Reg : {mse_lasso}")

MSE Lasso Reg : 0.6796290284328825


In [12]:
print(f"R2 Lasso Reg : {r2_lasso}")

R2 Lasso Reg : 0.48136113250290735


In [13]:
lasso_reg.coef_

array([ 0.71059779,  0.1064527 , -0.        ,  0.        , -0.        ,
       -0.        , -0.01146856, -0.        ])

##**Apply Ridge Regression**

---

In [14]:
ridge_reg = Ridge(alpha=1.0)
ridge_reg.fit(X_train, y_train)
y_pred_ridge = ridge_reg.predict(X_test)

mse_ridge = mean_squared_error(y_test, y_pred_ridge)
r2_ridge = r2_score(y_test, y_pred_ridge)

In [15]:
print(f"MSE Ridge Reg : {mse_ridge}")

MSE Ridge Reg : 0.5558548589435971


In [16]:
print(f"R2 Ridge Reg : {r2_ridge}")

R2 Ridge Reg : 0.5758157428913684


In [17]:
ridge_reg.coef_

array([ 0.85432679,  0.12262397, -0.29421036,  0.33900794, -0.00228221,
       -0.04083302, -0.89616759, -0.86907074])

In [18]:
ridge_reg.intercept_

2.0719469373788777

##**Elastic Net Regression**

---

In [19]:
elastic_net = ElasticNet(alpha=1, l1_ratio=0.5)
elastic_net.fit(X_train, y_train)

ElasticNet(alpha=1)

In [20]:
y_pred_elastic = elastic_net.predict(X_test)

In [21]:
mse_elastic = mean_squared_error(y_test, y_pred_ridge)
r2_elastic = r2_score(y_test, y_pred_ridge)

In [22]:
print(f"MSE Elastic Reg : {mse_elastic}")

MSE Elastic Reg : 0.5558548589435971


In [23]:
print(f"R2 Elastic Reg : {r2_elastic}")

R2 Elastic Reg : 0.5758157428913684


In [24]:
elastic_net.coef_

array([ 0.19901304,  0.        ,  0.        , -0.        , -0.        ,
       -0.        , -0.        , -0.        ])